/**
 * The test-only label fixture the moved component suites render with.
 *
 * The built-in `nb` pack is neutral; the suites these tests came from assert
 * the wording of the site they were written for. So that their assertions
 * could move unchanged, this fixture holds those exact strings for the keys
 * the moved tests read — and only where no business is named in them (those
 * keep the neutral pack's words, or the parity config's stand-in name).
 *
 * A whole pack — the built-in `nb` with these over it — the way a site hands
 * the components its resolved pack. Never shipped: it lives under tests/.
 */

import { mergeLabels } from '../../src/react/labels';
import { LOGIN_TEST_LABELS } from './labels-login';
import { MANAGE_TEST_LABELS } from './labels-manage';
import { PORTAL_TEST_LABELS } from './labels-portal';

export const TEST_LABELS = mergeLabels('nb-NO', {
  'addChild.birthYearPlaceholder': 'År',
  'addChild.description.saved':
    'Barnet lagres på Min side, så slipper du å skrive det inn neste gang.',
  'addChild.missing': 'Barnet trenger både navn og fødselsår.',
  'addChild.notes': 'Notat til frisøren (valgfritt)',
  'ageConfirm.birthMonth': 'Fødselsmåned (valgfritt)',
  'ageConfirm.dismiss': 'Ikke nå',
  'ageConfirm.heading': 'Bekreft alderen til {name}',
  'ageConfirm.lead': 'Legg til fødselsmåned for riktig alder.',
  'ageConfirm.legend': 'Alderen til {name}',
  'bookingSkeleton.opening': 'Åpner timebestillingen …',
  'childCards.book': 'Bestill for {name}',
  'childCards.empty': 'Ingen barn lagt til ennå.',
  'childCards.neverVisited': '{age} · ingen klipp hos oss ennå',
  'childCards.stylist': 'Fast frisør',
  'confirmation.calendar': 'Legg til i kalender',
  'confirmation.heading': 'Timen er bekreftet! 🎉',
  'confirmation.manage': 'Endre eller avbestill',
  'confirmation.manageFor': 'Endre eller avbestill {who} kl. {time}',
  'confirmation.party.heading': 'Familiebesøk · {day}',
  'confirmation.party.total': 'Totalt {total} · betales i salongen',
  'confirmation.portal': 'Se alle timene dine på Min side',
  'confirmation.startOver': 'Bestill ny time',
  'dataControls.consequences':
    'Kommende timer avbestilles, historikken anonymiseres, og du kan ikke logge inn igjen.',
  'dataControls.delete': 'Slett meg',
  'dataControls.deleteForever': 'Slett meg for alltid',
  'dataControls.export': 'Last ned mine data',
  'dataControls.unreachable':
    'Vi fikk ikke kontakt med bookingsystemet. Prøv igjen om et øyeblikk.',
  'dataControls.wrongWord': 'Skriv {word} med store bokstaver for å bekrefte.',
  'details.call.link': 'Ring oss på {phone}',
  'details.call.none': 'Ring oss, så hjelper vi deg.',
  'details.child.name': 'Hvem skal klippes?',
  'details.child.year': 'Fødselsår',
  'details.child.yearPlaceholder': '2017',
  'details.email.error': 'Sjekk e-postadressen – den ser ikke helt riktig ut.',
  'details.email.help': 'for bekreftelse og kalenderinvitasjon',
  'details.email.label': 'E-post',
  'details.error.conflict': 'Vi fikk ikke satt opp timen. Prøv en gang til.',
  'details.error.inProgress':
    'Vi har allerede fått denne bestillingen. Sjekk e-posten din – bekreftelsen kommer dit. Ser du den ikke om noen minutter, ring salongen.',
  'details.error.invalidInput': 'Noe i skjemaet stemmer ikke. Se over feltene og prøv igjen.',
  'details.error.maxParty': 'Vi kan ta opptil tre barn i samme booking.',
  'details.error.slotTaken': 'Tiden ble dessverre tatt mens du fylte ut. Velg et nytt tidspunkt.',
  'details.error.unconfigured': 'Vi får ikke tak i timeboken akkurat nå.',
  'details.error.upstreamError':
    'Vi vet ikke om timen ble satt opp – timeboken svarte ikke. Trykk «Bekreft time» en gang til, så finner vi ut av det uten å dobbeltbooke.',
  'details.heading': 'Nesten ferdig!',
  'details.known.for': 'for {who}',
  'details.known.label': 'Hvem som skal klippes',
  'details.name.label': 'Ditt navn',
  'details.notes.label': 'Noe vi bør vite?',
  'details.notes.placeholder': 'F.eks. første klipp, sensitiv for maskin …',
  'details.phone.error': 'Sjekk mobilnummeret – det ser ut som det mangler et siffer.',
  'details.phone.label': 'Mobilnummer',
  'details.submit': 'Bekreft time – {price} betales i salongen',
  'details.terms.link': '',
  'details.terms.text':
    'Jeg forstår at timen kan endres eller avbestilles gratis frem til fristen salongen har satt.',
  'familyEditor.add': 'Legg til barn',
  'familyEditor.ageConfirmed': 'Alderen til {name} er bekreftet.',
  'familyEditor.ageSaved': 'Alderen til {name} er lagret.',
  'familyEditor.birthMonth': 'Fødselsmåned (valgfritt)',
  'familyEditor.birthYearPlaceholder': 'År',
  'familyEditor.heading': 'Familie',
  'familyEditor.legend': 'Barn',
  'familyEditor.newRow': 'Nytt barn',
  'familyEditor.notes': 'Notat til frisøren',
  'familyEditor.partial': 'Barnet trenger både navn og fødselsår.',
  'familyEditor.removeRow': 'Fjern rad',
  'familyEditor.savedNoDetails':
    'Lagret. Måned, fast frisør og notat kan ikke lagres ennå – prøv igjen senere.',
  'familyEditor.stylist': 'Fast frisør',
  'familyEditor.stylistNone': 'Ingen fast',
  'familyEditor.unreachable':
    'Vi fikk ikke kontakt med bookingsystemet. Prøv igjen om et øyeblikk.',
  'history.heading': 'Historikk',
  'history.serviceFallback': 'Klipp',
  'login.codeHeading': 'Sjekk e-posten din',
  'login.codeHelp': 'Seks siffer – til {email}. Koden gjelder i ti minutter.',
  'login.codeLabel': 'Engangskode',
  'login.cooldownReady': 'Du kan be om en ny kode nå.',
  'login.emailIntro':
    'Logg inn med e-postadressen du brukte da du bestilte. Vi sender deg en engangskode.',
  'login.emailLabel': 'E-post',
  'login.notice.badEmail': 'Skriv inn en gyldig e-postadresse.',
  'login.notice.invalid': 'Feil kode, eller koden har gått ut. Prøv igjen eller be om en ny.',
  'login.notice.resent':
    'Hvis vi har e-postadressen din, har vi sendt en ny kode. Sjekk innboksen – og søppelposten.',
  'login.notice.sent':
    'Hvis vi har e-postadressen din, har du fått en kode. Sjekk innboksen – og søppelposten.',
  'login.notice.throttled': 'For mange forsøk. Vent litt før du prøver igjen.',
  'login.notice.unreachable':
    'Vi fikk ikke kontakt med bookingsystemet. Prøv igjen om et øyeblikk.',
  'login.notice.vippsConflict':
    'Denne Vipps-kontoen er allerede koblet til en annen profil. Logg inn med e-post, eller ring salongen.',
  'login.notice.vippsInvalid': 'Koden stemmer ikke eller har gått ut.',
  'login.resend': 'Send ny kode',
  'login.resendIn': 'Send ny kode om {time}',
  'login.sendCode': 'Send kode',
  'login.switchEmail': 'Bruk en annen e-post',
  'login.useEmailInstead': 'Logg inn med e-post i stedet',
  'login.vippsSentTo': 'Vi sendte en kode til {to}.',
  'login.vippsSentToUnknown': 'Vi har sendt en kode til e-postadressen salongen har på deg.',
  'loginSheet.intro':
    'Da fyller vi inn navn, nummer og barna dine, og timen havner i Min side – der du kan endre eller avbestille selv.',
  'loginSheet.prompt': 'Har du konto? {trigger} – så fyller vi inn navn og nummer for deg.',
  'logout.unreachable': 'Vi fikk ikke kontakt med bookingsystemet. Prøv igjen om et øyeblikk.',
  'manage.blocked': 'Mindre enn {hours} timer igjen –',
  'manage.blocked.plain': 'ring oss, så finner vi en løsning.',
  'manage.blocked.suffix': ', så finner vi en løsning.',
  'manage.bookNew': 'Bestill ny time',
  'manage.calendar': 'Legg til i kalender',
  'manage.callToCancel': 'Ring oss for å avbestille (mindre enn {hours} t igjen)',
  'manage.callToChange': 'Ring oss for å endre (mindre enn {hours} t igjen)',
  'manage.cancel.question':
    'Avbestille {appointment} {dateTime}? Det er gratis frem til {hours} t før.',
  'manage.cancelled': 'Timen er avbestilt. Vil du finne et nytt tidspunkt med en gang?',
  'manage.cancelled.findNew': 'Finn ny time',
  'manage.change': 'Endre tidspunkt',
  'manage.closed.completed': 'Denne timen er gjennomført.',
  'manage.closed.pendingCall': 'Ring oss på {phone}, så hjelper vi deg.',
  'manage.error.conflict': 'Timen kan ikke endres nå – {ringUs}, så finner vi en løsning.',
  'manage.error.invalidInput': 'Tidspunktet kunne ikke brukes. Velg en annen tid.',
  'manage.error.notFound': 'Vi finner ikke denne timen lenger. {callUs}, så hjelper vi deg.',
  'manage.error.slotTaken': 'Oi, den ble nettopp tatt. Velg en annen tid.',
  'manage.error.unavailable': 'Noe gikk galt hos oss. Prøv igjen, eller {ringUs}.',
  'manage.error.windowPassed':
    'Det er for kort tid igjen til å endre selv – {ringUs}, så finner vi en løsning.',
  'manage.freeUntil': 'Gratis endring frem til {dateTime}',
  'manage.heading': 'Timen din',
  'manage.move.confirm': 'Bekreft endring',
  'manage.moved.noLink': 'Endringen er registrert.',
  'manage.party.heading': 'Endre hele besøket, eller bare {who}?',
  'manage.party.note': 'De andre i familien beholder tidene sine. Skal hele besøket flyttes,',
  'manage.party.noteSuffix': ', så flytter vi alle sammen.',
  'manage.portal': 'Se alle timene dine på Min side',
  'manage.reschedule.failed': 'Vi får ikke hentet ledige tider akkurat nå –',
  'manage.reschedule.lead': '{service} – velg en ny tid',
  'manage.reschedule.leadWithStylist': '{service} hos {stylist} – velg en ny tid',
  'otp.label': 'Engangskode',
  'portalShell.nav': 'Min side',
  'portalShell.navBar': 'Min side',
  'portalUnreachable.body':
    'Timene dine er der fortsatt – det er vi som ikke får kontakt med timeboken. Prøv igjen om et øyeblikk, eller ring oss, så finner vi ut av det sammen.',
  'portalUnreachable.call': 'Ring oss på {phone}',
  'portalUnreachable.retry': 'Prøv igjen',
  'profileForm.email': 'E-post',
  'profileForm.heading': 'Om deg',
  'profileForm.phone': 'Mobilnummer',
  'profileForm.restored': 'Navn kan ikke være tomt – vi beholdt det gamle.',
  'profileForm.unreachable': 'Vi fikk ikke kontakt med bookingsystemet. Prøv igjen om et øyeblikk.',
  'rebook.anyStylist': 'Første ledige',
  'rebook.cta': 'Bestill samme',
  'rebook.empty': 'Når dere har vært hos oss, kan du bestille det samme igjen herfra.',
  'rebook.heading': 'Bestill igjen',
  'service.ageDivider.named': 'Passer vanligvis ikke for {nameGenitive} alder',
  'service.ageDivider.unnamed': 'Passer vanligvis ikke for barnets alder',
  'service.heading': 'Hva skal gjøres?',
  'service.party.adultAlone':
    '{label} kan ikke bookes sammen med barna – voksenklipp er en egen time.',
  'service.party.nothingFits': 'Ingen av tjenestene kan bookes for {label} i en så stor gruppe.',
  'service.party.remove': 'Ta bort {label} fra denne timen',
  'service.phoneOnly': 'Ring oss for denne',
  'service.phoneOnlyLinkLabel': 'Ring oss for denne – {phone}',
  'stylist.firstAvailableBadge': '⚡',
  'stylist.firstAvailableSubtitle': 'Vi finner den første ledige tiden',
  'stylist.heading': 'Hvem vil du gå til?',
  'stylist.loading': 'Henter frisører …',
  'stylist.party.legend': 'Hvordan skal barna tas?',
  'stylist.party.parallel.other': 'Flere frisører samtidig',
  'stylist.party.parallel.three': 'Tre frisører samtidig',
  'stylist.party.parallel.two': 'To frisører samtidig',
  'stylist.party.parallelMinutes': 'Inn og ut på {minutes} min',
  'stylist.party.parallelNote.other': 'Vi finner flere frisører som er ledige samtidig.',
  'stylist.party.parallelNote.three': 'Vi finner tre frisører som er ledige samtidig.',
  'stylist.party.parallelNote.two': 'Vi finner to frisører som er ledige samtidig.',
  'stylist.party.sequential': 'Samme frisør, rett etter hverandre',
  'stylist.pendingName': 'Valgt frisør',
  'summary.next': 'Neste',
  'summary.placeholder.service': 'Velg en tjeneste',
  'summary.placeholder.who': 'Velg hvem som skal klippes',
  'time.current': '{time} · Nåværende time',
  'time.empty.callPlain': 'ring oss, så finner vi en tid.',
  'time.empty.callSuffix': ', så finner vi en tid.',
  'time.empty.closed': 'Stengt {day} – velg en annen dag.',
  'time.empty.full': 'Fullt {day} –',
  'time.empty.over': 'For sent {day} – velg en annen dag.',
  'time.empty.stylist': '{stylist} har ingen ledige tider {day} –',
  'time.empty.unknown': 'Ingenting ledig {day} –',
  'time.heading': 'Når passer det?',
  'time.month.note': 'Vi åpner for booking sju dager fram. Trykk på en dag for å se ledige tider.',
  'time.month.show': 'Vis hele måneden',
  'time.nearest': 'nærmeste alternativ',
  'time.nextFree': 'Neste ledige time',
  'time.parallel.accept': 'Ta {time} samtidig',
  'time.parallel.offer.other':
    'Ingen ledige timer rett etter hverandre {day} – men alle kan tas samtidig kl. {time}.',
  'time.parallel.offer.two':
    'Ingen ledige timer rett etter hverandre {day} – men begge kan tas samtidig kl. {time}.',
  'time.shortNotice': 'Ring oss for time i dag på kort varsel',
  'time.taken.message': 'Oi, den ble nettopp tatt – her er nærmeste alternativer',
  'time.weekend.mixed': 'Lør/søn: med helgetillegg ({price})',
  'time.weekend.pct': 'Lør/søn: +{pct}\u00A0% helgetillegg ({price})',
  'upcoming.anyStylist': 'Første ledige',
  'upcoming.book': 'Bestill time',
  'upcoming.call': 'ring oss på {phone}',
  'upcoming.heading': 'Kommende timer',
  'upcoming.manage': 'Endre eller avbestill',
  'vipps.throttled': 'Prøv igjen om et øyeblikk.',
  'vipps.unavailable': 'Vipps-innlogging er ikke tilgjengelig akkurat nå. Bruk e-post i stedet.',
  'vippsLink.conflict':
    'Denne Vipps-kontoen er allerede koblet til en annen profil. Ring salongen om du trenger hjelp.',
  'vippsLink.failed': 'Vi fikk ikke koblet til Vipps. Prøv igjen.',
  'vippsLink.linked': 'Koblet til Vipps',
  'vippsLink.success': 'Vipps er koblet til',
  'vippsLink.throttled': 'Prøv igjen om et øyeblikk.',
  'vippsLink.unavailable': 'Vipps er ikke tilgjengelig akkurat nå. Prøv igjen senere.',
  'who.family.legend': 'Velg opptil tre',
  'who.family.limit': 'Vi tar opptil tre i samme booking.',
  'who.guest.groupLabel': 'Hvor mange skal klippes?',
  'who.heading': 'Hvem skal klippes?',
  'wizard.step.when': 'Frisør og tid',
  'wizard.stylistGone':
    'Frisøren du valgte er ikke ledig for denne bestillingen. Vi viser første ledige.',
  'wizard.who.lastVisitFallback': 'klipp',
  'wizard.ics.price': '{price} · betales i salongen',
  'category.barn': 'Barn',
  'category.dame': 'Dame',
  'category.herre': 'Herre',
  'category.farge': 'Farge',
  'category.annet': 'Annet',
  ...MANAGE_TEST_LABELS,
  ...PORTAL_TEST_LABELS,
  ...LOGIN_TEST_LABELS,
});
