#!/usr/bin/env node
// Keeps every copy of the package version in step with package.json:
//
//   - jsr.json `version`             (the JSR publish manifest)
//   - src/version.ts `SDK_VERSION`   (what the User-Agent header reports)
//   - openapi/*.yaml `info.version`  (the published contract's own version)
//
// Wired into `pnpm run version` right after `changeset version` bumps
// package.json, so a release carries the new number everywhere. Run with
// `--check` to VERIFY instead of write: it exits 1 naming every file that
// drifted, which is what CI and tests/version-sync.test.ts rely on.
//
// History: through 1.10.0 the User-Agent said `medalsocial-sdk/1.0.0` and the
// OpenAPI document said `1.1.7` — each was hand-edited once and never again.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const args = process.argv.slice(2);
const checkOnly = args.includes("--check");
const rootFlag = args.indexOf("--root");
const root =
  rootFlag !== -1 && args[rootFlag + 1]
    ? resolve(args[rootFlag + 1])
    : resolve(dirname(fileURLToPath(import.meta.url)), "..");

const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
const version = pkg.version;
if (typeof version !== "string" || !/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version)) {
  console.error(
    `[sync-version] package.json has no usable version (got ${JSON.stringify(version)})`,
  );
  process.exit(1);
}

/** @type {{ file: string; current: string | null; next: string }[]} */
const targets = [];

// jsr.json — a JSON rewrite that keeps the file's 2-space layout.
{
  const file = resolve(root, "jsr.json");
  const raw = readFileSync(file, "utf8");
  const json = JSON.parse(raw);
  const current = typeof json.version === "string" ? json.version : null;
  json.version = version;
  targets.push({ file, current, next: `${JSON.stringify(json, null, 2)}\n` });
  if (current === version) targets[targets.length - 1].next = raw;
}

// src/version.ts — the whole file is generated, so it is rewritten outright.
{
  const file = resolve(root, "src", "version.ts");
  const raw = readFileSync(file, "utf8");
  const match = raw.match(/SDK_VERSION = "([^"]*)"/);
  const current = match ? match[1] : null;
  const next = [
    "// GENERATED by scripts/sync-version.mjs from package.json — do not edit.",
    "// `pnpm run version` (the Changesets version step) rewrites this file, the",
    "// OpenAPI `info.version` and jsr.json together; tests/version-sync.test.ts",
    "// fails when any of them drifts from package.json.",
    "/** The published version of this SDK, as sent in the `User-Agent` header. */",
    `export const SDK_VERSION = "${version}";`,
    "",
  ].join("\n");
  targets.push({ file, current, next: current === version ? raw : next });
}

// openapi yaml — only the `version:` line inside the `info:` block is touched.
//
// A line walk rather than one multi-line regex: the block is delimited by
// indentation, and expressing "any indented lines, then `version:`" as a
// regex needs a nested quantifier (`(?:[ \t]+.*\n)*?`) whose `[ \t]+` and `.*`
// overlap — exponential backtracking, which CodeQL flags as js/redos.
{
  const file = resolve(root, "openapi", "medal-social.openapi.yaml");
  const raw = readFileSync(file, "utf8");
  // Split on `\n` only, so a `\r` stays on its line and the join below
  // reproduces the file's own line endings byte for byte.
  const lines = raw.split("\n");
  const infoAt = lines.findIndex((line) => /^info:\s*$/.test(line));
  let current = null;
  let next = raw;
  for (let i = infoAt === -1 ? lines.length : infoAt + 1; i < lines.length; i++) {
    const line = lines[i];
    if (!/^[ \t]/.test(line)) break; // dedent — the info block is over
    const match = line.match(/^([ \t]+version:[ \t]+)(\S+)/);
    if (!match) continue;
    current = match[2];
    lines[i] = `${match[1]}${version}${line.slice(match[0].length)}`;
    next = lines.join("\n");
    break;
  }
  targets.push({ file, current, next });
}

const drifted = targets.filter((t) => t.current !== version);

if (checkOnly) {
  if (drifted.length > 0) {
    console.error(`[sync-version] FAIL — package.json is ${version} but:`);
    for (const t of drifted) {
      console.error(`  - ${t.file} says ${t.current ?? "<missing>"}`);
    }
    console.error("Run `node scripts/sync-version.mjs` to bring them in step.");
    process.exit(1);
  }
  console.log(`[sync-version] OK — every copy of the version reads ${version}.`);
} else {
  for (const t of targets) {
    if (t.current === null) {
      console.error(`[sync-version] FAIL — could not find a version in ${t.file}`);
      process.exit(1);
    }
  }
  for (const t of drifted) {
    writeFileSync(t.file, t.next);
    console.log(`[sync-version] ${t.file}: ${t.current} -> ${version}`);
  }
  if (drifted.length === 0) {
    console.log(`[sync-version] OK — every copy of the version already reads ${version}.`);
  }
}
