/**
 * The built-in copy for every `@medalsocial/meda/booking` screen, in `nb` and
 * `en`: neutral wording with no business named in it. A site passes its own
 * words through `labels`, merged over these key by key (`mergeLabels`).
 *
 * Kept in step with meda's `BOOKING_LABEL_KEYS` by `tests/react/labels.test.ts`.
 */

import type { BookingLabels as MedaBookingLabels } from '@medalsocial/meda/booking';
import type { BookingLabel } from '../../core/labels';

/**
 * Every meda screen key, each a `BookingLabel`: a string renders as one text
 * node, an array one per element (meda ≥ 3.4). The built-in packs are all
 * strings.
 */
export type ScreenLabels = { [K in keyof MedaBookingLabels]-?: BookingLabel };

export const SCREEN_LABELS_NB: ScreenLabels = {
  'addChild.birthMonth': 'Fødselsmåned (valgfritt)',
  'addChild.birthMonthUnknown': 'Vet ikke',
  'addChild.birthYear': 'Fødselsår',
  'addChild.birthYearPlaceholder': 'Velg år',
  'addChild.close': 'Lukk',
  'addChild.description.local': 'Gjelder bare denne bestillingen.',
  'addChild.description.saved': 'Barnet lagres på profilen din til neste gang.',
  'addChild.missing': 'Skriv inn navn og velg fødselsår.',
  'addChild.name': 'Navn',
  'addChild.notes': 'Notat til salongen (valgfritt)',
  'addChild.submit': 'Legg til',
  'addChild.title': 'Legg til barn',
  'addChild.trigger': 'Legg til barn',
  'ageConfirm.birthMonth': 'Fødselsmåned (frivillig)',
  'ageConfirm.birthMonthUnknown': 'Vet ikke',
  'ageConfirm.birthYear': 'Fødselsår',
  'ageConfirm.confirm': 'Bekreft',
  'ageConfirm.dismiss': 'Senere',
  'ageConfirm.heading': 'Stemmer alderen til {name}?',
  'ageConfirm.lead': 'Legg gjerne inn fødselsmåned, så blir alderen helt riktig.',
  'ageConfirm.legend': 'Alder for {name}',
  'bookingSkeleton.opening': 'Laster timebestilling …',
  'childCards.book': 'Bestill til {name}',
  'childCards.empty': 'Ingen barn registrert ennå.',
  'childCards.lastVisit': '{age} · sist: {service}, {date}',
  'childCards.lastVisitNoService': '{age} · sist: {date}',
  'childCards.neverVisited': '{age} · ikke vært hos oss ennå',
  'childCards.next': 'Neste time',
  'childCards.none': '–',
  'childCards.stylist': 'Fast stylist',
  'confirmation.calendar': 'Legg i kalenderen',
  'confirmation.heading': 'Timen er bestilt',
  'confirmation.manage': 'Flytt eller avbestill',
  'confirmation.manageFor': 'Flytt eller avbestill {who} kl. {time}',
  'confirmation.party.heading': 'Felles besøk · {day}',
  'confirmation.party.line': '{time} {name} – {service} {stylist} – {price}',
  'confirmation.party.stylist': 'hos {name}',
  'confirmation.party.total': 'Til sammen {total} · betales i salongen',
  'confirmation.portal': 'Se alle timene dine',
  'confirmation.serviceFor': '{service} for {name}',
  'confirmation.startOver': 'Bestill en ny time',
  'confirmation.when': '{day} kl. {time}',
  'dataControls.cancel': 'Avbryt',
  'dataControls.confirmHeading': 'Vil du virkelig slette kontoen?',
  'dataControls.confirmHelp': 'Dette kan ikke gjøres om.',
  'dataControls.confirmLabel': 'Skriv {word} for å bekrefte',
  'dataControls.confirmWord': 'SLETT',
  'dataControls.consequences':
    'Timer du har bestilt, blir avbestilt, historikken blir anonymisert, og du kan ikke logge inn igjen.',
  'dataControls.delete': 'Slett kontoen',
  'dataControls.deleteForever': 'Slett kontoen for godt',
  'dataControls.export': 'Last ned en kopi',
  'dataControls.heading': 'Dataene dine',
  'dataControls.unreachable': 'Vi nådde ikke bookingsystemet. Prøv igjen straks.',
  'dataControls.wrongWord': 'Skriv {word} nøyaktig slik, med store bokstaver.',
  'details.call.link': 'Ring {phone}',
  'details.call.none': 'Ring salongen, så hjelper vi deg.',
  'details.child.name': 'Navn på den som kommer',
  'details.child.year': 'Født år',
  'details.child.yearPlaceholder': '2018',
  'details.email.error': 'E-postadressen ser ikke riktig ut.',
  'details.email.help': 'Vi sender bekreftelsen og en kalenderfil hit.',
  'details.email.label': 'E-postadresse',
  'details.email.lockedHelp': 'E-posten du logget inn med',
  'details.error.conflict': 'Timen kunne ikke settes opp. Prøv igjen.',
  'details.error.inProgress':
    'Bestillingen er allerede mottatt. Se etter bekreftelsen på e-post, eller ring oss.',
  'details.error.invalidInput': 'Noen felt er ikke riktig fylt ut. Se over og prøv igjen.',
  'details.error.maxParty': 'Du kan bestille for opptil tre personer om gangen.',
  'details.error.slotTaken': 'Noen andre rakk å ta tiden. Velg en ny tid.',
  'details.error.unconfigured': 'Timeboken er ikke tilgjengelig akkurat nå.',
  'details.error.upstreamError':
    'Vi fikk ikke svar fra timeboken, så vi vet ikke om timen ble registrert. Trykk på knappen igjen – du blir ikke booket to ganger.',
  'details.heading': 'Snart ferdig',
  'details.known.adult': 'en voksen',
  'details.known.child': 'barnet',
  'details.known.for': 'til {who}',
  'details.known.label': 'Timene gjelder',
  'details.known.self': 'deg',
  'details.marketing.text': 'Send meg påminnelser og tilbud på e-post.',
  'details.name.label': 'Navnet ditt',
  'details.notes.label': 'Beskjed til salongen',
  'details.notes.placeholder': 'For eksempel ønsker eller hensyn vi bør kjenne til',
  'details.phone.error': 'Mobilnummeret ser ikke komplett ut. Sjekk sifrene.',
  'details.phone.label': 'Mobil',
  'details.phone.prefix': '+47',
  'details.submit': 'Bestill – {price} betales i salongen',
  'details.terms.link': 'Les vilkårene',
  'details.terms.text': 'Jeg vet at timen kan flyttes eller avlyses gratis innen salongens frist.',
  'familyEditor.add': 'Legg til person',
  'familyEditor.ageConfirmed': 'Takk, alderen til {name} er bekreftet.',
  'familyEditor.ageSaved': 'Takk, alderen til {name} er lagret.',
  'familyEditor.birthMonth': 'Fødselsmåned (frivillig)',
  'familyEditor.birthMonthUnknown': 'Vet ikke',
  'familyEditor.birthYear': 'Fødselsår',
  'familyEditor.birthYearPlaceholder': 'Velg år',
  'familyEditor.empty': 'Ingen er lagt inn ennå.',
  'familyEditor.heading': 'Familien',
  'familyEditor.lead': 'Med alderen kan vi foreslå riktig behandling og pris for hver enkelt.',
  'familyEditor.legend': 'Familiemedlemmer',
  'familyEditor.name': 'Navn',
  'familyEditor.newRow': 'Ny person',
  'familyEditor.notes': 'Beskjed til stylisten',
  'familyEditor.notesPlaceholder': 'For eksempel: blir urolig av lyden fra maskinen',
  'familyEditor.partial': 'Fyll inn både navn og fødselsår.',
  'familyEditor.remove': 'Fjern',
  'familyEditor.removeNamed': 'Fjern {name}',
  'familyEditor.removeRow': 'Fjern raden',
  'familyEditor.removed': 'Fjernet',
  'familyEditor.save': 'Lagre',
  'familyEditor.saved': 'Lagret',
  'familyEditor.savedNoDetails':
    'Lagret. Måned, stylist og beskjed kunne ikke lagres nå – prøv igjen senere.',
  'familyEditor.stylist': 'Foretrukket stylist',
  'familyEditor.stylistFormer': 'Tidligere stylist',
  'familyEditor.stylistNone': 'Ingen bestemt',
  'familyEditor.unreachable': 'Vi nådde ikke bookingsystemet. Prøv igjen straks.',
  'history.count.one': '{count} besøk i {year}',
  'history.count.other': '{count} besøk i {year}',
  'history.empty': 'Ingen besøk ennå. Her dukker de opp etter første time.',
  'history.heading': 'Tidligere besøk',
  'history.serviceFallback': 'Besøk',
  'history.unknownAmount': '—',
  'login.codeHeading': 'Se etter koden i e-posten',
  'login.codeHelp': 'Seks sifre, sendt til {email}. Koden varer i ti minutter.',
  'login.codeHelpVipps': 'Seks sifre. Riktig kode kobler Vipps til kontoen din.',
  'login.codeLabel': 'Kode',
  'login.continueEmail': 'Fortsett med e-post',
  'login.cooldownReady': 'Nå kan du be om en ny kode.',
  'login.cooldownWait': 'Du kan be om en ny kode om {seconds} sekunder.',
  'login.emailIntro': 'Bruk e-postadressen du bestilte med, så sender vi deg en kode.',
  'login.emailLabel': 'E-postadresse',
  'login.heading': 'Logg inn',
  'login.notice.badEmail': 'Den e-postadressen ser ikke riktig ut.',
  'login.notice.invalid': 'Koden er feil eller utløpt. Prøv igjen, eller be om en ny.',
  'login.notice.resent':
    'Finnes adressen hos oss, er en ny kode på vei. Se i innboksen, og i søppelposten.',
  'login.notice.sent':
    'Finnes adressen hos oss, er en kode på vei. Se i innboksen, og i søppelposten.',
  'login.notice.throttled': 'For mange forsøk på kort tid. Vent litt.',
  'login.notice.unreachable': 'Vi når ikke timeboken akkurat nå. Prøv igjen straks.',
  'login.notice.vippsConflict':
    'Denne Vipps-kontoen hører til en annen konto hos oss. Logg inn med e-post, eller ring oss.',
  'login.notice.vippsInvalid': 'Koden er feil eller utløpt.',
  'login.or': 'eller',
  'login.resend': 'Send en ny kode',
  'login.resendIn': 'Ny kode om {time}',
  'login.sendCode': 'Send meg en kode',
  'login.submitCode': 'Logg inn',
  'login.switchEmail': 'Bytt e-postadresse',
  'login.useEmailInstead': 'Bruk e-post i stedet',
  'login.vippsSentTo': 'Koden er sendt til {to}.',
  'login.vippsSentToUnknown': 'Koden er sendt til e-postadressen vi har registrert på deg.',
  'loginSheet.close': 'Lukk',
  'loginSheet.intro': 'Vi fyller ut navn og nummer, og timen dukker opp på kontoen din.',
  'loginSheet.prompt': 'Kunde fra før? {trigger}, så fyller vi ut det vi vet.',
  'loginSheet.trigger': 'Logg inn',
  'loginSheet.vipps': 'Fortsett med Vipps',
  'logout.button': 'Logg ut',
  'logout.unreachable': 'Vi nådde ikke bookingsystemet. Prøv igjen straks.',
  'manage.appointment.named': '{name}s time',
  'manage.appointment.namedSibilant': "{name}' time",
  'manage.appointment.unnamed': 'timen',
  'manage.back': 'Tilbake',
  'manage.blocked': 'Under {hours} timer igjen –',
  'manage.blocked.plain': 'ring oss, så finner vi ut av det.',
  'manage.blocked.suffix': ', så finner vi ut av det.',
  'manage.bookNew': 'Bestill en ny time',
  'manage.calendar': 'Legg i kalenderen',
  'manage.callToCancel': 'Ring for å avbestille (under {hours} t igjen)',
  'manage.callToChange': 'Ring for å endre (under {hours} t igjen)',
  'manage.callUs': 'Ring oss',
  'manage.callUsOn': 'Ring oss på {phone}',
  'manage.cancel': 'Avbestill',
  'manage.cancel.confirm': 'Ja, avbestill',
  'manage.cancel.keep': 'Behold timen',
  'manage.cancel.question':
    'Avbestille {appointment} {dateTime}? Det er gratis fram til {hours} t før.',
  'manage.cancel.reason.illness': 'Sykdom',
  'manage.cancel.reason.noLongerSuits': 'Passer ikke lenger',
  'manage.cancel.reason.other': 'Annet',
  'manage.cancel.reasonLegend': 'Grunn (valgfritt)',
  'manage.cancelled': 'Timen er avbestilt. Vil du finne en ny tid med en gang?',
  'manage.cancelled.findNew': 'Finn en ny tid',
  'manage.card.named': '{name} – {service}',
  'manage.card.when': '{dateTime} · {price}',
  'manage.card.whenWithStylist': '{dateTime} hos {stylist} · {price}',
  'manage.change': 'Endre tid',
  'manage.closed.cancelled': 'Denne timen er avbestilt.',
  'manage.closed.completed': 'Denne timen er fullført.',
  'manage.closed.noShow': 'Denne timen er avsluttet.',
  'manage.closed.pending': 'Denne timen er ikke bekreftet ennå.',
  'manage.closed.pendingCall': 'Ta kontakt på {phone}, så ordner vi det.',
  'manage.closed.pendingCallPlain': 'Ring oss, så hjelper vi deg.',
  'manage.error.conflict': 'Timen kan ikke endres nå – {ringUs}.',
  'manage.error.invalidInput': 'Den tiden kan ikke brukes. Velg en annen.',
  'manage.error.notFound': 'Vi finner ikke denne timen. {callUs}, så hjelper vi deg.',
  'manage.error.slotTaken': 'Den tiden ble akkurat tatt. Velg en annen.',
  'manage.error.unavailable': 'Noe gikk galt. Prøv igjen, eller {ringUs}.',
  'manage.error.windowPassed': 'Det er for kort tid igjen til å endre selv – {ringUs}.',
  'manage.freeUntil': 'Gratis å endre fram til {dateTime}',
  'manage.heading': 'Din time',
  'manage.move.confirm': 'Bekreft ny tid',
  'manage.move.pickAnother': 'Velg en annen tid',
  'manage.move.question': 'Flytte {appointment} fra {from} til {to}?',
  'manage.move.questionWithStylist': 'Flytte {appointment} fra {from} til {to} hos {stylist}?',
  'manage.move.surcharge': 'Merk: {weekday}spris {price} (+{pct}\u00A0% helgetillegg)',
  'manage.moved': 'Timen er flyttet.',
  'manage.moved.noLink': 'Endringen er lagret.',
  'manage.moved.noLinkSuffix': 'hvis du vil endre den igjen.',
  'manage.moved.view': 'Se timen',
  'manage.movedTo': 'Timen er flyttet til {dateTime}.',
  'manage.party.heading': 'Flytte hele besøket, eller bare {who}?',
  'manage.party.justThisOne': 'Bare {who}',
  'manage.party.note': 'De andre beholder timene sine. Skal hele besøket flyttes,',
  'manage.party.noteSuffix': ', så flytter vi alle.',
  'manage.party.unnamed': 'denne timen',
  'manage.portal': 'Se alle timene dine',
  'manage.remaining.day.one': '{count} dag',
  'manage.remaining.day.other': '{count} dager',
  'manage.remaining.daysAndHours': 'om {days} og {hours}',
  'manage.remaining.hour.one': '{count} time',
  'manage.remaining.hour.other': '{count} timer',
  'manage.remaining.in': 'om {amount}',
  'manage.remaining.minute.one': '{count} minutt',
  'manage.remaining.minute.other': '{count} minutter',
  'manage.remaining.underMinute': 'om under ett minutt',
  'manage.reschedule.failed': 'Vi får ikke hentet ledige tider nå –',
  'manage.reschedule.failedSuffix': ', så finner vi en tid.',
  'manage.reschedule.lead': '{service} – velg ny tid',
  'manage.reschedule.leadWithStylist': '{service} hos {stylist} – velg ny tid',
  'manage.reschedule.loading': 'Henter ledige tider …',
  'manage.ringUs': 'ring oss',
  'manage.ringUsOn': 'ring oss på {phone}',
  'manage.serviceFallback': 'Time',
  'otp.label': 'Kode fra e-posten',
  'portalShell.nav': 'Kontoen din',
  'portalShell.navBar': 'Kontomeny',
  'portalUnreachable.body':
    'Timene dine ligger trygt – det er bare vi som ikke når timeboken. Prøv igjen straks, eller ring oss.',
  'portalUnreachable.call': 'Ring {phone}',
  'portalUnreachable.heading': 'Kontoen din er utilgjengelig akkurat nå',
  'portalUnreachable.retry': 'Last inn på nytt',
  'profileForm.email': 'E-postadresse',
  'profileForm.emailHelp': 'Vil du bytte e-postadresse, må du kontakte oss.',
  'profileForm.firstName': 'Fornavn',
  'profileForm.heading': 'Dine opplysninger',
  'profileForm.lastName': 'Etternavn',
  'profileForm.marketing': 'Ja takk, send meg nyheter og tilbud på e-post',
  'profileForm.phone': 'Mobil',
  'profileForm.restored': 'Navnet kan ikke stå tomt, så vi beholdt det du hadde.',
  'profileForm.save': 'Lagre',
  'profileForm.saved': 'Lagret',
  'profileForm.unreachable': 'Vi nådde ikke bookingsystemet. Prøv igjen straks.',
  'rebook.anyStylist': 'Hvem som helst',
  'rebook.cta': 'Bestill det samme',
  'rebook.empty': 'Etter første besøk kan du bestille det samme igjen herfra.',
  'rebook.heading': 'Bestill på nytt',
  'rebook.serviceFallback': 'Time',
  'service.ageDivider.named': 'Passer vanligvis ikke for alderen til {name}',
  'service.ageDivider.unnamed': 'Passer vanligvis ikke for alderen',
  'service.categoriesLegend': 'Kategorier',
  'service.chooseFirst': 'Velg minst én tjeneste',
  'service.chooseOther': 'Velg noe annet',
  'service.continue': 'Neste',
  'service.duration': '{minutes} min',
  'service.heading': 'Hva vil du bestille?',
  'service.multiHint': 'Velg én eller flere',
  'service.party.adultAlone': '{label} må bestilles som en egen time.',
  'service.party.listLabel': 'Tjenester for {label}',
  'service.party.nothingBookable': 'Ingen tjenester kan bestilles på nett for {label}.',
  'service.party.nothingFits': 'Ingen tjenester kan bestilles for {label} i en så stor gruppe.',
  'service.party.remove': 'Fjern {label} fra denne timen',
  'service.phoneOnly': 'Bestilles på telefon',
  'service.phoneOnlyLinkLabel': 'Bestilles på telefon – ring {phone}',
  'service.sameAsLast': 'Samme som sist',
  'service.tabDone': 'ferdig',
  'service.total': '{minutes} min · {price}',
  'stylist.firstAvailable': 'Første ledige',
  'stylist.firstAvailableBadge': '★',
  'stylist.firstAvailableSubtitle': 'Første stol som er ledig',
  'stylist.heading': 'Hvem vil du bestille hos?',
  'stylist.loading': 'Henter behandlere …',
  'stylist.nextAvailable': 'Neste ledige:',
  'stylist.party.legend': 'Hvordan vil dere ha timene?',
  'stylist.party.parallel.other': 'Flere behandlere samtidig',
  'stylist.party.parallel.three': 'Tre behandlere samtidig',
  'stylist.party.parallel.two': 'To behandlere samtidig',
  'stylist.party.parallelMinutes': 'Ferdig på {minutes} min',
  'stylist.party.parallelNote.other': 'Vi finner {count} behandlere som er ledige samtidig.',
  'stylist.party.parallelNote.three': 'Vi finner tre behandlere som er ledige samtidig.',
  'stylist.party.parallelNote.two': 'Vi finner to behandlere som er ledige samtidig.',
  'stylist.party.sequential': 'Samme behandler, etter hverandre',
  'stylist.party.sequentialMinutes': 'Til sammen {minutes} min',
  'stylist.pendingName': 'Valgt behandler',
  'summary.next': 'Videre',
  'summary.placeholder.service': 'Velg en behandling',
  'summary.placeholder.who': 'Velg hvem timen gjelder',
  'time.current': '{time} · Din time nå',
  'time.dayStrip.legend': 'Velg dag',
  'time.empty.callLink': 'ring oss på {phone}',
  'time.empty.callLinkAria': 'Ring oss på {phone}',
  'time.empty.callPlain': 'ring oss, så hjelper vi deg.',
  'time.empty.callSuffix': ', så hjelper vi deg.',
  'time.empty.closed': 'Stengt {day} – prøv en annen dag.',
  'time.empty.full': 'Fullbooket {day} –',
  'time.empty.over': 'Ikke flere tider {day} – prøv en annen dag.',
  'time.empty.stylist': '{stylist} er fullbooket {day} –',
  'time.empty.unknown': 'Ingen ledige tider {day} –',
  'time.heading': 'Når vil du komme?',
  'time.loading': 'Henter ledige tider …',
  'time.month.heading': '{month} {year}',
  'time.month.hide': 'Skjul måneden',
  'time.month.next': 'Neste måned',
  'time.month.note': 'Du kan bestille inntil sju dager fram. Velg en dag for å se ledige tider.',
  'time.month.previous': 'Forrige måned',
  'time.month.show': 'Se hele måneden',
  'time.nearest': 'nærmeste ledige',
  'time.nextFree': 'Første ledige time',
  'time.parallel.accept': 'Velg {time} samtidig',
  'time.parallel.offer.other':
    'Ingen tider etter hverandre {day} – men alle kan komme samtidig kl. {time}.',
  'time.parallel.offer.two':
    'Ingen tider etter hverandre {day} – men dere kan komme samtidig kl. {time}.',
  'time.party.parallel': '{time} ({seats})',
  'time.party.seat': '{who} hos {stylist}',
  'time.party.seatSeparator': ' · ',
  'time.party.sequential': '{start} → {end}',
  'time.shortNotice': 'Ring oss hvis du vil komme i dag',
  'time.skeleton.dayPlaceholder': 'man. 00.',
  'time.taken.close': 'Lukk',
  'time.taken.message': 'Den tiden ble akkurat tatt – her er de nærmeste',
  'time.weekend.mixed': 'Helg: inkludert helgetillegg ({price})',
  'time.weekend.pct': 'Helg: +{pct}\u00A0% helgetillegg ({price})',
  'upcoming.anyStylist': 'Hvem som helst',
  'upcoming.book': 'Bestill en time',
  'upcoming.call': 'ring {phone}',
  'upcoming.empty': 'Du har ingen timer framover.',
  'upcoming.heading': 'Neste timer',
  'upcoming.inDays': 'om {count} dager',
  'upcoming.manage': 'Flytt eller avlys',
  'upcoming.next': 'Neste time – {when}',
  'upcoming.noManage': 'Kontakt oss for å gjøre endringer.',
  'upcoming.noManageWithPhone': 'Kontakt oss for å gjøre endringer – {call}.',
  'upcoming.serviceFallback': 'Time',
  'upcoming.today': 'i dag',
  'upcoming.tomorrow': 'i morgen',
  'upcoming.when': '{day} kl. {time}',
  'vipps.button': 'Logg inn med Vipps',
  'vipps.throttled': 'Vent litt, og prøv igjen.',
  'vipps.unavailable': 'Innlogging med Vipps er nede akkurat nå. Bruk e-post i stedet.',
  'vippsLink.button': 'Koble til Vipps',
  'vippsLink.conflict':
    'Denne Vipps-kontoen hører allerede til en annen profil. Kontakt oss om du trenger hjelp.',
  'vippsLink.failed': 'Vi fikk ikke til å koble til Vipps. Prøv en gang til.',
  'vippsLink.heading': 'Vipps',
  'vippsLink.linked': 'Kontoen er koblet til Vipps',
  'vippsLink.pitch': 'Koble til Vipps, så logger du inn med ett trykk.',
  'vippsLink.success': 'Vipps er nå koblet til',
  'vippsLink.throttled': 'Vent litt, og prøv igjen.',
  'vippsLink.unavailable': 'Vipps er utilgjengelig akkurat nå. Prøv igjen litt senere.',
  'who.family.legend': 'Velg opptil {max}',
  'who.family.limit': 'En bestilling kan gjelde opptil {max} personer.',
  'who.family.self': 'Meg selv (voksen)',
  'who.guest.addedList': 'Barn i denne bestillingen',
  'who.guest.adult': 'Voksen',
  'who.guest.children.one': '{count} barn',
  'who.guest.children.other': '{count} barn',
  'who.guest.groupLabel': 'Hvor mange gjelder timen?',
  'who.heading': 'Hvem gjelder timen?',
};

export const SCREEN_LABELS_EN: ScreenLabels = {
  'addChild.birthMonth': 'Month of birth (optional)',
  'addChild.birthMonthUnknown': 'Not sure',
  'addChild.birthYear': 'Year of birth',
  'addChild.birthYearPlaceholder': 'Choose year',
  'addChild.close': 'Close',
  'addChild.description.local': 'Only for this booking.',
  'addChild.description.saved': 'We keep the child on your profile for next time.',
  'addChild.missing': 'Enter a name and choose a year of birth.',
  'addChild.name': 'Name',
  'addChild.notes': 'Note for the salon (optional)',
  'addChild.submit': 'Add',
  'addChild.title': 'Add a child',
  'addChild.trigger': 'Add a child',
  'ageConfirm.birthMonth': 'Month of birth (optional)',
  'ageConfirm.birthMonthUnknown': 'Not sure',
  'ageConfirm.birthYear': 'Year of birth',
  'ageConfirm.confirm': 'Confirm',
  'ageConfirm.dismiss': 'Later',
  'ageConfirm.heading': 'Is {name}’s age right?',
  'ageConfirm.lead': 'Add a birth month and we will get the age exactly right.',
  'ageConfirm.legend': 'Age for {name}',
  'bookingSkeleton.opening': 'Opening booking …',
  'childCards.book': 'Book for {name}',
  'childCards.empty': 'No children added yet.',
  'childCards.lastVisit': '{age} · last: {service}, {date}',
  'childCards.lastVisitNoService': '{age} · last: {date}',
  'childCards.neverVisited': '{age} · not been in yet',
  'childCards.next': 'Next appointment',
  'childCards.none': '–',
  'childCards.stylist': 'Usual stylist',
  'confirmation.calendar': 'Add to calendar',
  'confirmation.heading': 'You are booked in',
  'confirmation.manage': 'Change or cancel',
  'confirmation.manageFor': 'Change or cancel {who} at {time}',
  'confirmation.party.heading': 'Group visit · {day}',
  'confirmation.party.line': '{time} {name} – {service} {stylist} – {price}',
  'confirmation.party.stylist': 'with {name}',
  'confirmation.party.total': 'Total {total} · paid at the salon',
  'confirmation.portal': 'See all your bookings',
  'confirmation.serviceFor': '{service} for {name}',
  'confirmation.startOver': 'Book another appointment',
  'confirmation.when': '{day} at {time}',
  'dataControls.cancel': 'Cancel',
  'dataControls.confirmHeading': 'Really delete your account?',
  'dataControls.confirmHelp': 'This cannot be undone.',
  'dataControls.confirmLabel': 'Type {word} to confirm',
  'dataControls.confirmWord': 'DELETE',
  'dataControls.consequences':
    'Upcoming appointments are cancelled, your history is anonymised, and you will not be able to log in again.',
  'dataControls.delete': 'Delete my account',
  'dataControls.deleteForever': 'Delete my account for good',
  'dataControls.export': 'Download a copy',
  'dataControls.heading': 'Your data',
  'dataControls.unreachable': 'We could not reach the booking system. Please try again shortly.',
  'dataControls.wrongWord': 'Type {word} exactly, in capital letters.',
  'details.call.link': 'Call {phone}',
  'details.call.none': 'Call the salon and we will help.',
  'details.child.name': 'Name of the person coming',
  'details.child.year': 'Year of birth',
  'details.child.yearPlaceholder': '2018',
  'details.email.error': 'That email address does not look right.',
  'details.email.help': 'We send the confirmation and a calendar file here.',
  'details.email.label': 'Email address',
  'details.email.lockedHelp': 'The e-mail you signed in with',
  'details.error.conflict': 'We could not set up the appointment. Please try again.',
  'details.error.inProgress':
    'We already have this booking. Look for the confirmation email, or give us a call.',
  'details.error.invalidInput': 'Some fields are not filled in correctly. Please check them.',
  'details.error.maxParty': 'You can book for up to three people at a time.',
  'details.error.slotTaken': 'Someone else took that time. Please pick another.',
  'details.error.unconfigured': 'Online booking is unavailable right now.',
  'details.error.upstreamError':
    'The booking system did not answer, so we do not know if the appointment was made. Press the button again – you will not be booked twice.',
  'details.heading': 'Almost done',
  'details.known.adult': 'an adult',
  'details.known.child': 'your child',
  'details.known.for': 'for {who}',
  'details.known.label': 'These appointments are for',
  'details.known.self': 'you',
  'details.marketing.text': 'Send me reminders and offers by e-mail.',
  'details.name.label': 'Your name',
  'details.notes.label': 'Message for the salon',
  'details.notes.placeholder': 'Anything we should know in advance',
  'details.phone.error': 'That number looks incomplete. Please check the digits.',
  'details.phone.label': 'Mobile',
  'details.phone.prefix': '+44',
  'details.submit': 'Book – {price} paid at the salon',
  'details.terms.link': 'Read the terms',
  'details.terms.text':
    'I understand the appointment can be moved or cancelled free of charge before the salon’s deadline.',
  'familyEditor.add': 'Add a person',
  'familyEditor.ageConfirmed': 'Thanks, {name}’s age is confirmed.',
  'familyEditor.ageSaved': 'Thanks, {name}’s age is saved.',
  'familyEditor.birthMonth': 'Month of birth (optional)',
  'familyEditor.birthMonthUnknown': 'Not sure',
  'familyEditor.birthYear': 'Year of birth',
  'familyEditor.birthYearPlaceholder': 'Pick a year',
  'familyEditor.empty': 'Nobody added yet.',
  'familyEditor.heading': 'Your family',
  'familyEditor.lead': 'Knowing ages lets us suggest the right treatment and price for everyone.',
  'familyEditor.legend': 'Family members',
  'familyEditor.name': 'Name',
  'familyEditor.newRow': 'New person',
  'familyEditor.notes': 'Note for the stylist',
  'familyEditor.notesPlaceholder': 'For example: does not like the clipper noise',
  'familyEditor.partial': 'Please fill in both a name and a year of birth.',
  'familyEditor.remove': 'Remove',
  'familyEditor.removeNamed': 'Remove {name}',
  'familyEditor.removeRow': 'Remove this row',
  'familyEditor.removed': 'Removed',
  'familyEditor.save': 'Save',
  'familyEditor.saved': 'Saved',
  'familyEditor.savedNoDetails':
    'Saved. Month, stylist and note could not be stored right now – please try again later.',
  'familyEditor.stylist': 'Preferred stylist',
  'familyEditor.stylistFormer': 'Former stylist',
  'familyEditor.stylistNone': 'No preference',
  'familyEditor.unreachable': 'We could not reach the booking system. Please try again shortly.',
  'history.count.one': '{count} visit in {year}',
  'history.count.other': '{count} visits in {year}',
  'history.empty': 'No visits yet. They show up here after the first appointment.',
  'history.heading': 'Past visits',
  'history.serviceFallback': 'Visit',
  'history.unknownAmount': '—',
  'login.codeHeading': 'Check your e-mail for the code',
  'login.codeHelp': 'Six digits, sent to {email}. The code lasts ten minutes.',
  'login.codeHelpVipps': 'Six digits. The right code links Vipps to your account.',
  'login.codeLabel': 'Code',
  'login.continueEmail': 'Continue with e-mail',
  'login.cooldownReady': 'You can ask for a new code now.',
  'login.cooldownWait': 'You can ask for a new code in {seconds} seconds.',
  'login.emailIntro': 'Use the e-mail address you booked with and we will send you a code.',
  'login.emailLabel': 'E-mail address',
  'login.heading': 'Log in',
  'login.notice.badEmail': 'That e-mail address does not look right.',
  'login.notice.invalid': 'That code is wrong or expired. Try again, or ask for a new one.',
  'login.notice.resent':
    'If we know that address, a new code is on its way. Check your inbox, and your spam folder.',
  'login.notice.sent':
    'If we know that address, a code is on its way. Check your inbox, and your spam folder.',
  'login.notice.throttled': 'Too many tries in a short time. Wait a little.',
  'login.notice.unreachable': 'We cannot reach the booking system right now. Try again shortly.',
  'login.notice.vippsConflict':
    'This Vipps account belongs to another account with us. Log in with e-mail, or call us.',
  'login.notice.vippsInvalid': 'That code is wrong or expired.',
  'login.or': 'or',
  'login.resend': 'Send a new code',
  'login.resendIn': 'New code in {time}',
  'login.sendCode': 'Send me a code',
  'login.submitCode': 'Log in',
  'login.switchEmail': 'Use a different address',
  'login.useEmailInstead': 'Use e-mail instead',
  'login.vippsSentTo': 'The code went to {to}.',
  'login.vippsSentToUnknown': 'The code went to the e-mail address we have on file for you.',
  'loginSheet.close': 'Close',
  'loginSheet.intro': 'We fill in your name and number, and the booking shows up in your account.',
  'loginSheet.prompt': 'Been here before? {trigger} and we fill in what we know.',
  'loginSheet.trigger': 'Log in',
  'loginSheet.vipps': 'Continue with Vipps',
  'logout.button': 'Log out',
  'logout.unreachable': 'We could not reach the booking system. Please try again shortly.',
  'manage.appointment.named': "{name}'s appointment",
  'manage.appointment.namedSibilant': "{name}' appointment",
  'manage.appointment.unnamed': 'the appointment',
  'manage.back': 'Back',
  'manage.blocked': 'Under {hours} hours left –',
  'manage.blocked.plain': 'call us and we will sort it out.',
  'manage.blocked.suffix': ' and we will sort it out.',
  'manage.bookNew': 'Book a new appointment',
  'manage.calendar': 'Add to calendar',
  'manage.callToCancel': 'Call to cancel (under {hours} h left)',
  'manage.callToChange': 'Call to change (under {hours} h left)',
  'manage.callUs': 'Call us',
  'manage.callUsOn': 'Call us on {phone}',
  'manage.cancel': 'Cancel',
  'manage.cancel.confirm': 'Yes, cancel',
  'manage.cancel.keep': 'Keep the appointment',
  'manage.cancel.question': 'Cancel {appointment} {dateTime}? It is free until {hours} h before.',
  'manage.cancel.reason.illness': 'Illness',
  'manage.cancel.reason.noLongerSuits': 'No longer suits',
  'manage.cancel.reason.other': 'Other',
  'manage.cancel.reasonLegend': 'Reason (optional)',
  'manage.cancelled': 'The appointment is cancelled. Would you like to find a new time now?',
  'manage.cancelled.findNew': 'Find a new time',
  'manage.card.named': '{name} – {service}',
  'manage.card.when': '{dateTime} · {price}',
  'manage.card.whenWithStylist': '{dateTime} with {stylist} · {price}',
  'manage.change': 'Change time',
  'manage.closed.cancelled': 'This appointment has been cancelled.',
  'manage.closed.completed': 'This appointment has been completed.',
  'manage.closed.noShow': 'This appointment is closed.',
  'manage.closed.pending': 'This appointment is not confirmed yet.',
  'manage.closed.pendingCall': 'Call us on {phone} and we will help.',
  'manage.closed.pendingCallPlain': 'Call us and we will help.',
  'manage.error.conflict': 'The appointment cannot be changed right now – {ringUs}.',
  'manage.error.invalidInput': 'That time cannot be used. Please choose another.',
  'manage.error.notFound': 'We cannot find this appointment. {callUs} and we will help.',
  'manage.error.slotTaken': 'That time was just taken. Please choose another.',
  'manage.error.unavailable': 'Something went wrong. Try again, or {ringUs}.',
  'manage.error.windowPassed': 'It is too late to change this yourself – {ringUs}.',
  'manage.freeUntil': 'Free to change until {dateTime}',
  'manage.heading': 'Your appointment',
  'manage.move.confirm': 'Confirm new time',
  'manage.move.pickAnother': 'Choose another time',
  'manage.move.question': 'Move {appointment} from {from} to {to}?',
  'manage.move.questionWithStylist': 'Move {appointment} from {from} to {to} with {stylist}?',
  'manage.move.surcharge': 'Note: {weekday} price {price} (+{pct}\u00A0% weekend surcharge)',
  'manage.moved': 'The appointment has been moved.',
  'manage.moved.noLink': 'The change is saved.',
  'manage.moved.noLinkSuffix': 'if you want to change it again.',
  'manage.moved.view': 'View the appointment',
  'manage.movedTo': 'The appointment has been moved to {dateTime}.',
  'manage.party.heading': 'Move the whole visit, or just {who}?',
  'manage.party.justThisOne': 'Just {who}',
  'manage.party.note': 'Everyone else keeps their times. To move the whole visit,',
  'manage.party.noteSuffix': ' and we will move everyone.',
  'manage.party.unnamed': 'this appointment',
  'manage.portal': 'See all your appointments',
  'manage.remaining.day.one': '{count} day',
  'manage.remaining.day.other': '{count} days',
  'manage.remaining.daysAndHours': 'in {days} and {hours}',
  'manage.remaining.hour.one': '{count} hour',
  'manage.remaining.hour.other': '{count} hours',
  'manage.remaining.in': 'in {amount}',
  'manage.remaining.minute.one': '{count} minute',
  'manage.remaining.minute.other': '{count} minutes',
  'manage.remaining.underMinute': 'in under a minute',
  'manage.reschedule.failed': 'We cannot load free times right now –',
  'manage.reschedule.failedSuffix': ' and we will find a time.',
  'manage.reschedule.lead': '{service} – choose a new time',
  'manage.reschedule.leadWithStylist': '{service} with {stylist} – choose a new time',
  'manage.reschedule.loading': 'Loading free times …',
  'manage.ringUs': 'call us',
  'manage.ringUsOn': 'call us on {phone}',
  'manage.serviceFallback': 'Appointment',
  'otp.label': 'One-time code',
  'portalShell.nav': 'Your account',
  'portalShell.navBar': 'Account menu',
  'portalUnreachable.body':
    'Your bookings are safe – we just cannot reach the booking system. Try again shortly, or call us.',
  'portalUnreachable.call': 'Call {phone}',
  'portalUnreachable.heading': 'Your account is unavailable right now',
  'portalUnreachable.retry': 'Reload',
  'profileForm.email': 'E-mail address',
  'profileForm.emailHelp': 'To change your e-mail address, please get in touch with us.',
  'profileForm.firstName': 'First name',
  'profileForm.heading': 'Your details',
  'profileForm.lastName': 'Last name',
  'profileForm.marketing': 'Yes, e-mail me news and offers',
  'profileForm.phone': 'Mobile',
  'profileForm.restored': 'A name cannot be empty, so we kept the one you had.',
  'profileForm.save': 'Save',
  'profileForm.saved': 'Saved',
  'profileForm.unreachable': 'We could not reach the booking system. Please try again shortly.',
  'rebook.anyStylist': 'Anyone available',
  'rebook.cta': 'Book the same',
  'rebook.empty': 'After your first visit you can book the same again from here.',
  'rebook.heading': 'Book again',
  'rebook.serviceFallback': 'Appointment',
  'service.ageDivider.named': 'Usually not suited to {nameGenitive} age',
  'service.ageDivider.unnamed': 'Usually not suited to this age',
  'service.categoriesLegend': 'Categories',
  'service.chooseFirst': 'Choose at least one service',
  'service.chooseOther': 'Choose something else',
  'service.continue': 'Next',
  'service.duration': '{minutes} min',
  'service.heading': 'What would you like to book?',
  'service.multiHint': 'Choose one or more',
  'service.party.adultAlone': '{label} needs a separate appointment.',
  'service.party.listLabel': 'Services for {label}',
  'service.party.nothingBookable': 'Nothing can be booked online for {label}.',
  'service.party.nothingFits': 'Nothing can be booked for {label} in a group this size.',
  'service.party.remove': 'Remove {label} from this appointment',
  'service.phoneOnly': 'Book by phone',
  'service.phoneOnlyLinkLabel': 'Book by phone – call {phone}',
  'service.sameAsLast': 'Same as last time',
  'service.tabDone': 'done',
  'service.total': '{minutes} min · {price}',
  'stylist.firstAvailable': 'First available',
  'stylist.firstAvailableBadge': '★',
  'stylist.firstAvailableSubtitle': 'We find the first free time',
  'stylist.heading': 'Who would you like to see?',
  'stylist.loading': 'Loading stylists …',
  'stylist.nextAvailable': 'Next free:',
  'stylist.party.legend': 'How would you like the appointments?',
  'stylist.party.parallel.other': 'Several stylists at once',
  'stylist.party.parallel.three': 'Three stylists at once',
  'stylist.party.parallel.two': 'Two stylists at once',
  'stylist.party.parallelMinutes': 'Done in {minutes} min',
  'stylist.party.parallelNote.other': 'We find {count} stylists who are free at the same time.',
  'stylist.party.parallelNote.three': 'We find three stylists who are free at the same time.',
  'stylist.party.parallelNote.two': 'We find two stylists who are free at the same time.',
  'stylist.party.sequential': 'Same stylist, one after the other',
  'stylist.party.sequentialMinutes': '{minutes} min in total',
  'stylist.pendingName': 'Chosen stylist',
  'summary.next': 'Continue',
  'summary.placeholder.service': 'Choose a service',
  'summary.placeholder.who': 'Choose who the booking is for',
  'time.current': '{time} · Your current time',
  'time.dayStrip.legend': 'Choose a day',
  'time.empty.callLink': 'call us on {phone}',
  'time.empty.callLinkAria': 'Call us on {phone}',
  'time.empty.callPlain': 'call us and we will help.',
  'time.empty.callSuffix': ' and we will help.',
  'time.empty.closed': 'Closed {day} – try another day.',
  'time.empty.full': 'Fully booked {day} –',
  'time.empty.over': 'No more times {day} – try another day.',
  'time.empty.stylist': '{stylist} is fully booked {day} –',
  'time.empty.unknown': 'No free times {day} –',
  'time.heading': 'When would you like to come?',
  'time.loading': 'Loading free times …',
  'time.month.heading': '{month} {year}',
  'time.month.hide': 'Hide the month',
  'time.month.next': 'Next month',
  'time.month.note': 'You can book up to seven days ahead. Choose a day to see free times.',
  'time.month.previous': 'Previous month',
  'time.month.show': 'See the whole month',
  'time.nearest': 'nearest available',
  'time.nextFree': 'First available time',
  'time.parallel.accept': 'Take {time} together',
  'time.parallel.offer.other':
    'No back-to-back times {day} – but you can all come at the same time at {time}.',
  'time.parallel.offer.two':
    'No back-to-back times {day} – but you can both come at the same time at {time}.',
  'time.party.parallel': '{time} ({seats})',
  'time.party.seat': '{who} with {stylist}',
  'time.party.seatSeparator': ' · ',
  'time.party.sequential': '{start} → {end}',
  'time.shortNotice': 'Call us if you want to come today',
  'time.skeleton.dayPlaceholder': 'Mon 00',
  'time.taken.close': 'Close',
  'time.taken.message': 'That time was just taken – here are the nearest ones',
  'time.weekend.mixed': 'Weekend: surcharge included ({price})',
  'time.weekend.pct': 'Weekend: +{pct}\u00A0% surcharge ({price})',
  'upcoming.anyStylist': 'Anyone available',
  'upcoming.book': 'Book an appointment',
  'upcoming.call': 'call {phone}',
  'upcoming.empty': 'You have no appointments coming up.',
  'upcoming.heading': 'Coming up',
  'upcoming.inDays': 'in {count} days',
  'upcoming.manage': 'Move or cancel',
  'upcoming.next': 'Next appointment – {when}',
  'upcoming.noManage': 'Contact us to make changes.',
  'upcoming.noManageWithPhone': 'Contact us to make changes – {call}.',
  'upcoming.serviceFallback': 'Appointment',
  'upcoming.today': 'today',
  'upcoming.tomorrow': 'tomorrow',
  'upcoming.when': '{day} at {time}',
  'vipps.button': 'Log in with Vipps',
  'vipps.throttled': 'Wait a moment and try again.',
  'vipps.unavailable': 'Vipps login is down right now. Use e-mail instead.',
  'vippsLink.button': 'Link Vipps',
  'vippsLink.conflict':
    'This Vipps account already belongs to another profile. Get in touch if you need help.',
  'vippsLink.failed': 'We could not link Vipps. Please try once more.',
  'vippsLink.heading': 'Vipps',
  'vippsLink.linked': 'Your account is linked to Vipps',
  'vippsLink.pitch': 'Link Vipps and log in with a single tap next time.',
  'vippsLink.success': 'Vipps is now linked',
  'vippsLink.throttled': 'Please wait a moment and try again.',
  'vippsLink.unavailable': 'Vipps is unavailable right now. Please try again a little later.',
  'who.family.legend': 'Choose up to {max}',
  'who.family.limit': 'One booking can include up to {max} people.',
  'who.family.self': 'Myself (adult)',
  'who.guest.addedList': 'Children in this booking',
  'who.guest.adult': 'Adult',
  'who.guest.children.one': '{count} child',
  'who.guest.children.other': '{count} children',
  'who.guest.groupLabel': 'How many people?',
  'who.heading': 'Who is the appointment for?',
};
