/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/posts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List posts */
    get: operations["listPosts"];
    put?: never;
    /** Create a post */
    post: operations["createPost"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/posts/channels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List connected post channels */
    get: operations["listPostChannels"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/posts/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    /** Get post detail */
    get: operations["getPost"];
    put?: never;
    post?: never;
    /** Delete a post */
    delete: operations["deletePost"];
    options?: never;
    head?: never;
    /** Update a draft post */
    patch: operations["updatePost"];
    trace?: never;
  };
  "/api/v1/posts/{id}/schedule": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Schedule a post */
    post: operations["schedulePost"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/posts/{id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish a post */
    post: operations["publishPost"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/emails": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a transactional email */
    post: operations["sendEmail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/emails/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a batch of transactional emails */
    post: operations["batchSendEmails"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/emails/templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List active email templates */
    get: operations["listEmailTemplates"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/emails/templates/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: components["parameters"]["Slug"];
      };
      cookie?: never;
    };
    /** Get an email template */
    get: operations["getEmailTemplate"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/emails/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    /** Get sent email status */
    get: operations["getEmailSend"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/generate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate text with the workspace's configured LLM */
    post: operations["generateText"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/contacts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List contacts */
    get: operations["listContacts"];
    put?: never;
    /** Create a contact */
    post: operations["createContact"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/contacts/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import contacts */
    post: operations["importContacts"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/contacts/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    /** Get a contact */
    get: operations["getContact"];
    put?: never;
    post?: never;
    /** Delete a contact */
    delete: operations["deleteContact"];
    options?: never;
    head?: never;
    /** Update a contact */
    patch: operations["updateContact"];
    trace?: never;
  };
  "/api/v1/contacts/{id}/activities": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    /** List contact activities */
    get: operations["listContactActivities"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/contacts/{id}/notes": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add a contact note */
    post: operations["addContactNote"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/deals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List deals */
    get: operations["listDeals"];
    put?: never;
    /** Create a deal */
    post: operations["createDeal"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/deals/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    /** Get a deal */
    get: operations["getDeal"];
    put?: never;
    post?: never;
    /** Delete a deal */
    delete: operations["deleteDeal"];
    options?: never;
    head?: never;
    /** Update a deal */
    patch: operations["updateDeal"];
    trace?: never;
  };
  "/api/v1/gdpr/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a GDPR export */
    post: operations["requestGdprExport"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/gdpr/exports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List GDPR exports */
    get: operations["listGdprExports"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/gdpr/exports/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    /** Get a GDPR export */
    get: operations["getGdprExport"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/gdpr/consent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Record GDPR consent */
    post: operations["recordGdprConsent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/gdpr/consent/{email}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        email: string;
      };
      cookie?: never;
    };
    /** Get GDPR consent records */
    get: operations["getGdprConsent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cookie-consent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Record cookie consent */
    post: operations["recordCookieConsent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List accessible workspaces */
    get: operations["listWorkspaces"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiError: {
      error: {
        code: string;
        message: string;
        details?: unknown;
      };
    };
    Pagination: {
      has_more: boolean;
      next_cursor: string | null;
    };
    Success: {
      success: boolean;
    };
    PostCreateResult: {
      id: string;
    };
    Post: {
      id: string;
      type: components["schemas"]["PostType"];
      title: string | null;
      content: string;
      status: string;
      channel_ids: string[];
      variant_count: number;
      published_count: number;
      failed_count: number;
      /** Format: date-time */
      scheduled_at: string | null;
      /** Format: date-time */
      published_at: string | null;
      /** Format: date-time */
      created_at: string | null;
      /** Format: date-time */
      updated_at: string | null;
    };
    /** @enum {string} */
    PostType: "social" | "newsletter" | "blog";
    PostVariant: {
      id: string;
      channel_id: string;
      content: string;
      status: string;
      platform: string | null;
      channel_display_name: string | null;
      /** Format: date-time */
      scheduled_at: string | null;
      /** Format: date-time */
      published_at: string | null;
      platform_post_id: string | null;
      /** Format: uri */
      permalink: string | null;
      error: string | null;
    };
    PostDetail: components["schemas"]["Post"] & {
      variants: components["schemas"]["PostVariant"][];
    };
    Channel: {
      id: string;
      platform: string | null;
      display_name: string | null;
      platform_username: string | null;
      state: string;
      /** Format: date-time */
      connected_at: string | null;
    };
    CreatePostInput: {
      type?: components["schemas"]["PostType"];
      title?: string;
      content: string;
      channel_ids: string[];
    };
    UpdatePostInput: {
      title?: string;
      content?: string;
    };
    SchedulePostInput: {
      scheduled_at: number | string;
    };
    ScheduleResult: {
      success: boolean;
      workflow_id: string;
    };
    PublishResult: {
      success: boolean;
      workflow_id: string;
    };
    GenerateTextInput: {
      /** @description Prompt to send to the model. Supports {{placeholder}} substitution when variables is provided. */
      prompt: string;
      /** @description Model id in provider/model form. Defaults to the workspace's selected model. */
      model?: string;
      /** @description Override the system prompt. When omitted, the workspace brand context is used. */
      system_prompt?: string;
      temperature?: number;
      max_tokens?: number;
      use_brand_context?: boolean;
      use_skills?: boolean;
      variables?: {
        [key: string]: string;
      };
    };
    GenerateTextResult: {
      text: string;
      model: string;
      usage: {
        input_tokens: number;
        output_tokens: number;
      };
    };
    SendEmailInput: {
      template_slug: string;
      /** Format: email */
      to: string;
      name?: string;
      locale?: string;
      fallback_locale?: string;
      variables?: {
        [key: string]: string;
      };
      contact_id?: string;
    };
    EmailSendResult: {
      id: string;
      status: string;
    };
    EmailSend: {
      id: string;
      status: string;
      /** Format: email */
      recipient_email: string;
      recipient_name: string | null;
      subject: string | null;
      template_id: string | null;
      contact_id: string | null;
      /** Format: date-time */
      queued_at: string | null;
      /** Format: date-time */
      sent_at: string | null;
      /** Format: date-time */
      delivered_at: string | null;
      /** Format: date-time */
      opened_at: string | null;
      /** Format: date-time */
      clicked_at: string | null;
      error_message: string | null;
    };
    BatchSendInput: {
      template_slug: string;
      default_locale?: string;
      recipients: {
        /** Format: email */
        email: string;
        name?: string;
        locale?: string;
        variables?: {
          [key: string]: string;
        };
      }[];
    };
    BatchSendSummary: {
      batch_id: string;
      total: number;
      queued: number;
      failed: number;
    };
    EmailTemplate: {
      id: string;
      name: string;
      slug: string;
      type: string | null;
      subject: string | null;
      default_locale: string;
      available_locales: string[];
      description: string | null;
      category: string | null;
      label_ids: string[];
      is_active: boolean;
      is_archived: boolean;
      version: number;
      /** Format: date-time */
      created_at: string | null;
      /** Format: date-time */
      updated_at: string | null;
    };
    EmailTemplateDetail: components["schemas"]["EmailTemplate"] & {
      html_content: string | null;
      text_content: string | null;
      preview_text: string | null;
      from_name: string | null;
      /** Format: email */
      from_email: string | null;
      /** Format: email */
      reply_to: string | null;
      requested_locale: string | null;
      resolved_locale: string;
      content_source: string;
      localizations: {
        locale: string | null;
        subject: string | null;
        html_content: string | null;
        text_content: string | null;
        preview_text: string | null;
      }[];
    };
    Contact: {
      id: string;
      /** Format: email */
      email: string;
      first_name: string | null;
      last_name: string | null;
      phone: string | null;
      company: string | null;
      job_title: string | null;
      address: {
        [key: string]: string;
      } | null;
      status: components["schemas"]["ContactStatus"];
      email_status: components["schemas"]["EmailStatus"];
      label_ids: string[];
      source: string | null;
      custom_fields: {
        [key: string]: unknown;
      } | null;
      /** Format: date-time */
      created_at: string | null;
      /** Format: date-time */
      updated_at: string | null;
    };
    ContactCreateResult: {
      id: string;
    };
    ContactUpdateResult: {
      /** @constant */
      success: true;
    };
    ContactRemoveResult: {
      /** @constant */
      success: true;
    };
    ContactNoteResult: {
      id: string;
    };
    /** @enum {string} */
    ContactStatus: "lead" | "prospect" | "customer" | "churned" | "archived";
    /** @enum {string} */
    EmailStatus: "subscribed" | "unsubscribed" | "bounced" | "complained";
    CreateContactInput: {
      /** Format: email */
      email: string;
      first_name?: string;
      last_name?: string;
      phone?: string;
      company?: string;
      job_title?: string;
      address?: {
        [key: string]: string;
      };
      status?: components["schemas"]["ContactStatus"];
      email_status?: components["schemas"]["EmailStatus"];
      label_ids?: string[];
      labels?: string[];
      custom_fields?: {
        [key: string]: unknown;
      };
      notes?: string | components["schemas"]["ContactNoteInput"];
    };
    UpdateContactInput: {
      /** Format: email */
      email?: string;
      first_name?: string;
      last_name?: string;
      phone?: string;
      company?: string;
      job_title?: string;
      status?: components["schemas"]["ContactStatus"];
      email_status?: components["schemas"]["EmailStatus"];
      label_ids?: string[];
      labels?: string[];
      custom_fields?: {
        [key: string]: unknown;
      };
    };
    ContactNoteInput: {
      content: string;
      attachments?: {
        /** Format: uri */
        url: string;
        name: string;
        type?: string;
        size?: number;
      }[];
    };
    ImportContactInput: {
      /** Format: email */
      email: string;
      first_name?: string;
      last_name?: string;
      phone?: string;
      company?: string;
      job_title?: string;
      label_ids?: string[];
      status?: string;
    };
    ImportContactsResult: {
      added: number;
      skipped: number;
      total: number;
    };
    Activity: {
      id: string;
      type: string;
      title: string | null;
      content: string | null;
      actor_name: string | null;
      actor_type: string | null;
      metadata: unknown;
      /** Format: date-time */
      created_at: string | null;
    };
    AddNoteInput: {
      content: string;
    };
    Deal: {
      id: string;
      title: string;
      description: string | null;
      value: number | null;
      currency: string | null;
      status: components["schemas"]["DealStatus"];
      brand_name: string | null;
      /** Format: uri */
      brand_website: string | null;
      contact_id: string | null;
      contact_name: string | null;
      /** Format: email */
      contact_email: string | null;
      /** Format: date */
      start_date: string | null;
      /** Format: date */
      end_date: string | null;
      notes: string | null;
      /** Format: date-time */
      created_at: string | null;
      /** Format: date-time */
      updated_at: string | null;
    };
    DealCreateResult: {
      id: string;
    };
    DealUpdateResult: {
      /** @constant */
      success: true;
    };
    DealRemoveResult: {
      /** @constant */
      success: true;
    };
    /** @enum {string} */
    DealStatus:
      | "draft"
      | "open"
      | "won"
      | "lost"
      | "negotiating"
      | "proposal_sent"
      | "on_hold"
      | "churned";
    CreateDealInput: {
      title: string;
      description?: string;
      value?: number;
      currency?: string;
      brand_name?: string;
      /** Format: uri */
      brand_website?: string;
      contact_id?: string;
      contact_name?: string;
      /** Format: email */
      contact_email?: string;
      /** Format: date */
      start_date?: string;
      /** Format: date */
      end_date?: string;
      notes?: string;
    };
    UpdateDealInput: {
      title?: string;
      description?: string;
      value?: number;
      currency?: string;
      status?: components["schemas"]["DealStatus"];
      brand_name?: string;
      /** Format: uri */
      brand_website?: string;
      contact_id?: string | null;
      contact_name?: string;
      /** Format: email */
      contact_email?: string;
      /** Format: date */
      start_date?: string;
      /** Format: date */
      end_date?: string;
      notes?: string;
    };
    GdprExport: {
      id: string;
      request_type: string;
      status: string;
      /** Format: date-time */
      submitted_at: string | null;
      /** Format: date-time */
      completed_at: string | null;
      /** Format: date-time */
      due_date?: string | null;
      /** Format: uri */
      download_url?: string | null;
      /** Format: date-time */
      expires_at?: string | null;
    };
    GdprExportRequest: {
      request_id: string;
      status: string;
    };
    /** @enum {string} */
    ConsentType: "marketing_email" | "analytics_tracking" | "third_party_sharing";
    RecordConsentInput: {
      /** Format: email */
      email: string;
      consent_type: components["schemas"]["ConsentType"];
      granted: boolean;
      source?: string;
      ip_address?: string;
      consent_text?: string;
      version?: string;
    };
    ConsentRecord: {
      id: string;
      /** Format: email */
      email: string;
      consent_type: components["schemas"]["ConsentType"];
      granted: boolean;
      /** Format: date-time */
      granted_at: string | null;
      /** Format: date-time */
      revoked_at: string | null;
      source?: string;
      version?: string;
    };
    ConsentResult: {
      id: string;
    };
    CookieConsentInput: {
      domain: string;
      consentStatus: string;
      /** Format: date-time */
      consentTimestamp: string;
      ipAddress?: string;
      userAgent?: string;
      cookiePreferences: {
        [key: string]: components["schemas"]["CookieCategoryConsent"];
      };
    };
    CookieCategoryConsent: {
      allowed: boolean;
      cookieRecords?: {
        cookie: string;
        duration: string;
        description: string;
      }[];
    };
    CookieConsentResult: {
      success: boolean;
      logId?: string;
    };
    Workspace: {
      id: string;
      name: string;
      slug: string;
    } & {
      [key: string]: unknown;
    };
    ApiResponse_PostCreateResult: components["schemas"]["Envelope_PostCreateResult"];
    ApiResponse_PostDetail: components["schemas"]["Envelope_PostDetail"];
    ApiResponse_Success: components["schemas"]["Envelope_Success"];
    ApiResponse_ScheduleResult: components["schemas"]["Envelope_ScheduleResult"];
    ApiResponse_PublishResult: components["schemas"]["Envelope_PublishResult"];
    ApiResponse_ChannelArray: components["schemas"]["Envelope_ChannelArray"];
    ApiResponse_GenerateTextResult: components["schemas"]["Envelope_GenerateTextResult"];
    ApiResponse_EmailSendResult: components["schemas"]["Envelope_EmailSendResult"];
    ApiResponse_EmailSend: components["schemas"]["Envelope_EmailSend"];
    ApiResponse_BatchSendSummary: components["schemas"]["Envelope_BatchSendSummary"];
    ApiResponse_EmailTemplateArray: components["schemas"]["Envelope_EmailTemplateArray"];
    ApiResponse_EmailTemplateDetail: components["schemas"]["Envelope_EmailTemplateDetail"];
    ApiResponse_Contact: components["schemas"]["Envelope_Contact"];
    ApiResponse_ContactCreateResult: components["schemas"]["Envelope_ContactCreateResult"];
    ApiResponse_ContactUpdateResult: components["schemas"]["Envelope_ContactUpdateResult"];
    ApiResponse_ContactRemoveResult: components["schemas"]["Envelope_ContactRemoveResult"];
    ApiResponse_ContactNoteResult: components["schemas"]["Envelope_ContactNoteResult"];
    ApiResponse_ImportContactsResult: components["schemas"]["Envelope_ImportContactsResult"];
    ApiResponse_Deal: components["schemas"]["Envelope_Deal"];
    ApiResponse_DealCreateResult: components["schemas"]["Envelope_DealCreateResult"];
    ApiResponse_DealUpdateResult: components["schemas"]["Envelope_DealUpdateResult"];
    ApiResponse_DealRemoveResult: components["schemas"]["Envelope_DealRemoveResult"];
    ApiResponse_GdprExportRequest: components["schemas"]["Envelope_GdprExportRequest"];
    ApiResponse_GdprExportArray: components["schemas"]["Envelope_GdprExportArray"];
    ApiResponse_GdprExport: components["schemas"]["Envelope_GdprExport"];
    ApiResponse_ConsentResult: components["schemas"]["Envelope_ConsentResult"];
    ApiResponse_ConsentRecordArray: components["schemas"]["Envelope_ConsentRecordArray"];
    ApiResponse_WorkspaceArray: components["schemas"]["Envelope_WorkspaceArray"];
    PaginatedResponse_Post: {
      data: components["schemas"]["Post"][];
      pagination: components["schemas"]["Pagination"];
    };
    PaginatedResponse_Contact: {
      data: components["schemas"]["Contact"][];
      pagination: components["schemas"]["Pagination"];
    };
    PaginatedResponse_Activity: {
      data: components["schemas"]["Activity"][];
      pagination: components["schemas"]["Pagination"];
    };
    PaginatedResponse_Deal: {
      data: components["schemas"]["Deal"][];
      pagination: components["schemas"]["Pagination"];
    };
    Envelope_PostCreateResult: {
      data: components["schemas"]["PostCreateResult"];
    };
    Envelope_PostDetail: {
      data: components["schemas"]["PostDetail"];
    };
    Envelope_Success: {
      data: components["schemas"]["Success"];
    };
    Envelope_ScheduleResult: {
      data: components["schemas"]["ScheduleResult"];
    };
    Envelope_PublishResult: {
      data: components["schemas"]["PublishResult"];
    };
    Envelope_ChannelArray: {
      data: components["schemas"]["Channel"][];
    };
    Envelope_GenerateTextResult: {
      data: components["schemas"]["GenerateTextResult"];
    };
    Envelope_EmailSendResult: {
      data: components["schemas"]["EmailSendResult"];
    };
    Envelope_EmailSend: {
      data: components["schemas"]["EmailSend"];
    };
    Envelope_BatchSendSummary: {
      data: components["schemas"]["BatchSendSummary"];
    };
    Envelope_EmailTemplateArray: {
      data: components["schemas"]["EmailTemplate"][];
    };
    Envelope_EmailTemplateDetail: {
      data: components["schemas"]["EmailTemplateDetail"];
    };
    Envelope_Contact: {
      data: components["schemas"]["Contact"];
    };
    Envelope_ContactCreateResult: {
      data: components["schemas"]["ContactCreateResult"];
    };
    Envelope_ContactUpdateResult: {
      data: components["schemas"]["ContactUpdateResult"];
    };
    Envelope_ContactRemoveResult: {
      data: components["schemas"]["ContactRemoveResult"];
    };
    Envelope_ContactNoteResult: {
      data: components["schemas"]["ContactNoteResult"];
    };
    Envelope_ImportContactsResult: {
      data: components["schemas"]["ImportContactsResult"];
    };
    Envelope_Deal: {
      data: components["schemas"]["Deal"];
    };
    Envelope_DealCreateResult: {
      data: components["schemas"]["DealCreateResult"];
    };
    Envelope_DealUpdateResult: {
      data: components["schemas"]["DealUpdateResult"];
    };
    Envelope_DealRemoveResult: {
      data: components["schemas"]["DealRemoveResult"];
    };
    Envelope_GdprExportRequest: {
      data: components["schemas"]["GdprExportRequest"];
    };
    Envelope_GdprExportArray: {
      data: components["schemas"]["GdprExport"][];
    };
    Envelope_GdprExport: {
      data: components["schemas"]["GdprExport"];
    };
    Envelope_ConsentResult: {
      data: components["schemas"]["ConsentResult"];
    };
    Envelope_ConsentRecordArray: {
      data: components["schemas"]["ConsentRecord"][];
    };
    Envelope_WorkspaceArray: {
      data: components["schemas"]["Workspace"][];
    };
  };
  responses: {
    /** @description API error. */
    ApiError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ApiError"];
      };
    };
  };
  parameters: {
    Id: string;
    Slug: string;
    Cursor: string;
    Limit: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listPosts: {
    parameters: {
      query?: {
        limit?: components["parameters"]["Limit"];
        cursor?: components["parameters"]["Cursor"];
        status?: string;
        type?: components["schemas"]["PostType"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Posts page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedResponse_Post"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  createPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePostInput"];
      };
    };
    responses: {
      /** @description Created post reference. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_PostCreateResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  listPostChannels: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Connected channels. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ChannelArray"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  getPost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Post detail. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_PostDetail"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  deletePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Delete result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_Success"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  updatePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePostInput"];
      };
    };
    responses: {
      /** @description Update result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_Success"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  schedulePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SchedulePostInput"];
      };
    };
    responses: {
      /** @description Schedule result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ScheduleResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  publishPost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Publish result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_PublishResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  sendEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendEmailInput"];
      };
    };
    responses: {
      /** @description Email queued. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_EmailSendResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  batchSendEmails: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchSendInput"];
      };
    };
    responses: {
      /** @description Batch queued. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_BatchSendSummary"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  listEmailTemplates: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active templates. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_EmailTemplateArray"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  getEmailTemplate: {
    parameters: {
      query?: {
        locale?: string;
        fallback_locale?: string;
      };
      header?: never;
      path: {
        slug: components["parameters"]["Slug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Email template detail. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_EmailTemplateDetail"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  getEmailSend: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sent email status. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_EmailSend"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  generateText: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateTextInput"];
      };
    };
    responses: {
      /** @description Generated text. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_GenerateTextResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  listContacts: {
    parameters: {
      query?: {
        limit?: components["parameters"]["Limit"];
        cursor?: components["parameters"]["Cursor"];
        status?: components["schemas"]["ContactStatus"];
        email_status?: components["schemas"]["EmailStatus"];
        /** @description Comma-separated label IDs. */
        label_ids?: string;
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Contacts page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedResponse_Contact"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  createContact: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateContactInput"];
      };
    };
    responses: {
      /** @description Created contact reference. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ContactCreateResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  importContacts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          contacts: components["schemas"]["ImportContactInput"][];
        };
      };
    };
    responses: {
      /** @description Import summary. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ImportContactsResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  getContact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Contact. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_Contact"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  deleteContact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Delete result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ContactRemoveResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  updateContact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateContactInput"];
      };
    };
    responses: {
      /** @description Update result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ContactUpdateResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  listContactActivities: {
    parameters: {
      query?: {
        limit?: components["parameters"]["Limit"];
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Contact activities page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedResponse_Activity"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  addContactNote: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddNoteInput"];
      };
    };
    responses: {
      /** @description Created note reference. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ContactNoteResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  listDeals: {
    parameters: {
      query?: {
        limit?: components["parameters"]["Limit"];
        cursor?: components["parameters"]["Cursor"];
        status?: components["schemas"]["DealStatus"];
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deals page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedResponse_Deal"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  createDeal: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDealInput"];
      };
    };
    responses: {
      /** @description Created deal reference. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_DealCreateResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  getDeal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deal. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_Deal"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  deleteDeal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Delete result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_DealRemoveResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  updateDeal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateDealInput"];
      };
    };
    responses: {
      /** @description Update result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_DealUpdateResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  requestGdprExport: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Export request reference. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_GdprExportRequest"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  listGdprExports: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Export requests. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_GdprExportArray"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  getGdprExport: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Export request. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_GdprExport"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  recordGdprConsent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecordConsentInput"];
      };
    };
    responses: {
      /** @description Consent reference. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ConsentResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  getGdprConsent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        email: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Consent records. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ConsentRecordArray"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  recordCookieConsent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CookieConsentInput"];
      };
    };
    responses: {
      /** @description Cookie consent result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CookieConsentResult"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
  listWorkspaces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspaces. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_WorkspaceArray"];
        };
      };
      default: components["responses"]["ApiError"];
    };
  };
}
