// GENERATED by scripts/sync-version.mjs from package.json — do not edit.
// `pnpm run version` (the Changesets version step) rewrites this file, the
// OpenAPI `info.version` and jsr.json together; tests/version-sync.test.ts
// fails when any of them drifts from package.json.
/** The published version of this SDK, as sent in the `User-Agent` header. */
export const SDK_VERSION = "1.10.0";
